### PR TITLE
add support for tomcat 8

### PR DESCRIPTION
**Pull request by tcollignon**
To do this, I have updated to cargo 1.4.18
Thanks @dmytryk for help

### CODE REVIEW

**Comment by rkrzewski** [comment]
The patch looks good! I'll build it on my machine and give Tomcat 8 a spin later this week.

**Comment by tcollignon** [comment]
Cool ! Thank you

**Comment by tcollignon** [comment]
Hi,
May wait a few time because I'm thinking if there is a bug with snapshot dependencies.
Because of Tomcat 8 new managing of Resources (https://tomcat.apache.org/tomcat-8.0-doc/config/resources.html), a jar dependencies will be like that in server.xml file : 

````
 <PostResources base="/Volumes/Macintosh_HD_2/Work/mavenRepository/com/oracle/ojdbc6/11.2.0.4" className="org.apache.catalina.webresources.DirResourceSet" webAppMount="/WEB-INF/lib"/>
````

But if the dependencies is a SNAPSHOT, the parent folder in maven repository may have many jars inside, and I think there will be a problem.

I'm still searching a good way to write Tomcat8 configuration in Cargo, and I think I add new commit in this PR.

If you have good idea on this, let me know

**Comment by tcollignon** [comment]
I have open an issue on cargo project : https://codehaus-cargo.atlassian.net/browse/CARGO-1367
I will fix soon, and bring back new version here when it be released

**Comment by tcollignon** [comment]
Hi, with release of cargo 1.4.19 is now good for this PR !
The bug fix are : 
- https://codehaus-cargo.atlassian.net/browse/CARGO-1367
- https://codehaus-cargo.atlassian.net/browse/CARGO-1373

Let me know if you want something more Rafal.

**Comment by rkrzewski** [comment]
I've tested it locally using Tomcat 8.0.33. Everything works fine.
Thank you for your contribution!

**Pull request merged**
